# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "newrelic_api"
  s.version = "2.0.0-ey.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["New Relic"]
  s.date = "2012-05-24"
  s.description = "Use this gem to access New Relic application information via a REST api"
  s.email = "support@newrelic.com"
  s.extra_rdoc_files = [
    "CHANGELOG",
    "README.rdoc"
  ]
  s.files = `git ls-files`.split("\n")
  s.homepage = "http://www.github.com/newrelic/newrelic_api"
  s.licenses = ["MIT"]
  s.rdoc_options = ["--line-numbers", "--title", "Documentation and helper code for the New Relic API", "-m", "README.rdoc"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Documentation and helper code for the New Relic API"
  s.test_files = [
    "test/integration/newrelic_api_test.rb",
    "test/test_helper.rb"
  ]

  s.add_dependency 'activeresource', '~> 4.0', '>= 4.0.0'
end

